name: Publish to NPM
on:
    push:
        tags:
            - "[0-9]+.[0-9]+.[0-9]+"
permissions:
    contents: read
    id-token: write
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v4
              with:
                  node-version: "24.x"
                  id: publish
            - run: npm install
            - run: npm run build
            - run: npm publish
